# Generated by Django 4.2.13 on 2024-07-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiexcel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelchat',
            name='category',
            field=models.CharField(choices=[('Formula', 'Formula'), ('Rule', 'Rule'), ('Syntax', 'Syntax'), ('Project Idea', 'Project Idea')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='excelchat',
            name='question',
            field=models.TextField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='excelchat',
            index=models.Index(fields=['category'], name='aiexcel_exc_categor_848fe0_idx'),
        ),
        migrations.AddIndex(
            model_name='excelchat',
            index=models.Index(fields=['question'], name='aiexcel_exc_questio_7ac937_idx'),
        ),
    ]
