# Generated by Django 5.0.6 on 2024-06-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiexcel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelPage',
        ),
        migrations.DeleteModel(
            name='Formula',
        ),
    ]
