# Generated by Django 4.2.13 on 2024-07-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiexcel', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Formula', 'Formula'), ('Rule', 'Rule'), ('Syntax', 'Syntax'), ('Project Idea', 'Project Idea')], max_length=50)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
