# Generated by Django 4.2.13 on 2024-07-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiexcel', '0004_excelknowledge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelKnowledge',
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='response',
            field=models.JSONField(),
        ),
    ]
