# Generated by Django 4.2.13 on 2024-07-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiexcel', '0006_excelknowledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelknowledge',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='excelknowledge',
            table='aiexcel_excelknowledge',
        ),
    ]
